In [1]:
%load_ext nb_black

<IPython.core.display.Javascript object>

In [5]:
# install required packages
import os
import torch

os.environ["TORCH"] = torch.__version__
print(torch.__version__)
# Helper function for visualization.
%matplotlib inline
import networkx as nx
import matplotlib.pyplot as plt
import os
import collections
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.sparse as sp
import torch
from torch import Tensor
import torch_geometric
from torch_geometric.utils import to_networkx
from torch_geometric.datasets import Planetoid
import networkx as nx
from networkx.algorithms import community
# Set random seed for reproducibility
import numpy as np



2.0.1


<IPython.core.display.Javascript object>

In [6]:
from node2vec_def.node2vec import Node2Vec

<IPython.core.display.Javascript object>

In [7]:
SEED = 42
np.random.seed(SEED)

<IPython.core.display.Javascript object>

In [8]:
# def visualize_graph(G, color):
#     plt.figure(figsize=(7, 7))
#     plt.xticks([])
#     plt.yticks([])
#     nx.draw_networkx(
#         G,
#         pos=nx.spring_layout(G, seed=SEED),
#         with_labels=False,
#         node_color=color,
#         cmap="Set1",
#     )
#     plt.show()

<IPython.core.display.Javascript object>

In [9]:
def visualize_graph(G, color):
    plt.figure(figsize=(7, 7))
    plt.xticks([])
    plt.yticks([])

    pos = nx.spring_layout(G, seed=SEED)

    # Draw nodes with labels (node numbers)
    node_labels = {node: str(node) for node in G.nodes()}
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=10)

    nx.draw_networkx(
        G,
        pos=pos,
        with_labels=False,
        node_color=color,
        cmap="Set1",
    )

    plt.show()

<IPython.core.display.Javascript object>

In [10]:
from torch_geometric.datasets import KarateClub

dataset = KarateClub()

<IPython.core.display.Javascript object>

In [11]:
dataset

KarateClub()

<IPython.core.display.Javascript object>

In [12]:
print("Dataset properties")
print("==============================================================")
print(f"Dataset: {dataset}")  # This prints the name of the dataset
print(f"Number of graphs in the dataset: {len(dataset)}")
print(
    f"Number of features: {dataset.num_features}"
)  # Number of features each node in the dataset has
print(
    f"Number of classes: {dataset.num_classes}"
)  # Number of classes that a node can be classified into

Dataset properties
Dataset: KarateClub()
Number of graphs in the dataset: 1
Number of features: 34
Number of classes: 4


<IPython.core.display.Javascript object>

In [ ]:
print(dataset.weights)

In [13]:
data = dataset[0]
print("Graph properties")
print("==============================================================")

# Gather some statistics about the graph.
print(f"Number of nodes: {data.num_nodes}")  # Number of nodes in the graph
print(f"Number of edges: {data.num_edges}")  # Number of edges in the graph
print(
    f"Average node degree: {data.num_edges / data.num_nodes:.2f}"
)  # Average number of nodes in the graph
print(
    f"Contains isolated nodes: {data.has_isolated_nodes()}"
)  # Does the graph contains nodes that are not connected
print(
    f"Contains self-loops: {data.has_self_loops()}"
)  # Does the graph contains nodes that are linked to themselves
print(f"Is undirected: {data.is_undirected()}")  # Is the graph an undirected graph

Graph properties
Number of nodes: 34
Number of edges: 156
Average node degree: 4.59
Contains isolated nodes: False
Contains self-loops: False
Is undirected: True


<IPython.core.display.Javascript object>

In [14]:
type(data)

torch_geometric.data.data.Data

<IPython.core.display.Javascript object>

In [ ]:
data

In [ ]:
# Access edge connections (edge_index) and edge attributes (edge_attr)
edge_index = data.edge_index
edge_attr = data.edge_attr

print("Edge Index (Connections):")
print(edge_index)



In [ ]:
print("\nEdge Attributes (Weights):")
print(edge_attr)

In [ ]:
# Calculate the number of edges in the graph
num_edges = data.edge_index.shape[1]

In [ ]:
num_edges

In [ ]:
# Generate random weights for each edge (you can replace this with your own weighting logic)
edge_weights = torch.rand(num_edges)

In [ ]:
edge_weights

In [ ]:
# Add edge weights as edge attributes to the Data object
data.edge_attr = edge_weights

In [ ]:
# Print the updated Data object with edge weights
print(data.edge_attr)

In [15]:
from torch_geometric.utils import to_networkx

G = to_networkx(data, to_undirected=True)

<IPython.core.display.Javascript object>

In [16]:
G

<IPython.core.display.Javascript object>

In [17]:
data.y

tensor([1, 1, 1, 1, 3, 3, 3, 1, 0, 1, 3, 1, 1, 1, 0, 0, 3, 1, 0, 1, 0, 1, 0, 0,
        2, 2, 0, 0, 2, 0, 0, 2, 0, 0])

<IPython.core.display.Javascript object>

In [ ]:
club_labels

In [ ]:

# Now you can access the edge weights in the NetworkX graph
for u, v, weight in G.edges(data='weight'):
    print(f"Edge ({u}, {v}) has weight {weight:.4f}")

In [ ]:
# Now you can access the edge weights directly from data.edge_attr
for i, (u, v) in enumerate(data.edge_index.T.tolist()):
    weight = data.edge_attr[i].item()
    print(f"Edge ({u}, {v}) has weight {weight:.4f}")

In [ ]:
# Define node positions using a spring layout
import matplotlib.pyplot as plt

pos = nx.spring_layout(G, seed=SEED)

# Create a Matplotlib figure and axis
fig, ax = plt.subplots()

# Draw nodes and edges
nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=300,
    node_color="skyblue",
    font_size=12,
    font_color="black",
    font_weight="bold",
    edge_color="gray",
    ax=ax,
)

# Add a title
ax.set_title("Graph with High Structural and Community Similarity")

# Show the plot
plt.axis("off")
plt.show()

In [ ]:
visualize_graph(G, color=data.y)

In [ ]:
# Extract the node labels from the graph
node_labels = {node: G.nodes[node]['label'] for node in G.nodes()}

# Call the visualize_graph function with the graph and node_labels
# visualize_graph(G, node_labels)

In [ ]:
node_labels

In [ ]:
# Create a simple graph
G = nx.Graph()
G.add_edge(1, 2, weight=1.0)

In [ ]:
# import networkx as nx
# import random

# # Create an empty graph
# G = nx.Graph()

# # Add nodes from 0 to 9
# G.add_nodes_from(range(10))

# # Connect nodes randomly with random weights
# for i in range(10):
#     for j in range(i+1, 15):
#         if random.random() < 0.5:  # Adjust the probability as needed
#             weight = random.uniform(0.1, 5.0)  # Random weight between 0.1 and 5.0
#             G.add_edge(i, j, weight=weight)

# # Print the edges with their weights
# for edge in G.edges(data=True):
#     print(f"Edge {edge[0]} - {edge[1]}, Weight: {edge[2]['weight']}")

import networkx as nx
import random

# Create an empty graph
G = nx.Graph()

# Add nodes from 0 to 9
G.add_nodes_from(range(40))

# Assign random labels between 0 and 4 to the nodes
for node in G.nodes():
    label = random.randint(0, 4)  # Random label between 0 and 4
    G.nodes[node]['label'] = label

# Connect nodes randomly with random weights
for i in range(10):
    for j in range(i+1, 40):
        if random.random() < 0.5:  # Adjust the probability as needed
            weight = random.uniform(0.1, 5.0)  # Random weight between 0.1 and 5.0
            G.add_edge(i, j, weight=weight)

# Print the nodes with their labels and edges with their weights
for node in G.nodes(data=True):
    print(f"Node {node[0]}, Label: {node[1]['label']}")

for edge in G.edges(data=True):
    print(f"Edge {edge[0]} - {edge[1]}, Weight: {edge[2]['weight']}")

#### 'dimensions': 8, 'walk_length': 6, 'num_walks': 5, 'p': 1.5, 'q': 2.0, 'learning_rate': 0.001, 'window_size': 6, 'epochs': 125, 'negative_samples': 15, 'batch_size': 8
#### Best Loss: 111.7859431493728

In [18]:
dimensions = 8
walk_length = 10
num_walks = 10
p = 1.5
q = 4.0
learning_rate = 0.01
window_size = 6
epochs = 200
negative_samples = 6
batch_size = 8

<IPython.core.display.Javascript object>

In [ ]:
p = 1.0  # Return parameter
q = 1.0  # In-out parameter
utw = Node2Vec(G, p, q)

In [ ]:
# Create a NetworkX graph and add edges with weights
G = nx.Graph()

# Assuming you have edge data (u, v, weight) in your data
for edge in zip(data.edge_index[0], data.edge_index[1], data.edge_attr):
    u, v, weight = edge
    G.add_edge(u, v, weight=weight)

In [ ]:
G.nodes()

In [ ]:
# Preprocess transition probabilities
utw.preprocess_transition_probs()

In [ ]:
# Generate random walks
num_walks = 10
walk_length = 5
walks = []
# walks = node2vec.simulate_walks(num_walks, walk_length)


In [ ]:
for node in G.nodes():
    if utw.alias_nodes.get(node) is not None:
        walks.extend(utw.simulate_walks(num_walks, walk_length))

# Print the generated walks
for walk in walks:
    print(walk)

In [ ]:
G.edges()

In [ ]:
print(G.nodes())

In [ ]:
walks

In [ ]:
graph = Node2Vec(G, p, q, num_walks, walk_length)

In [ ]:
graph

In [ ]:
graph.preprocess_transition_probs()

In [ ]:
G.nodes()

In [ ]:
walks = graph.simulate_walks(num_walks, walk_length)

In [ ]:
import matplotlib.pyplot as plt
from gensim.models import Word2Vec

def learn_embeddings(walks, dimensions=128, window_size=5, epochs=10,negative=negative_samples,):
    '''
    Learn embeddings by optimizing the Skipgram objective using SGD and plot the loss values.

    Parameters:
        walks (list of lists): List of walks or sentences for training the Word2Vec model.
        dimensions (int): The size of the embedding vectors.
        window_size (int): The maximum distance between the current and predicted word within a sentence.
        epochs (int): The number of iterations (epochs) over the dataset.

    Returns:
        (numpy.ndarray, list): A tuple containing the embedding matrix and a list of loss values over epochs.
    '''
    # Convert the walks to string format if they are not already
    walks = [list(map(str, walk)) for walk in walks]

    # Create a Word2Vec model and train it
    model = Word2Vec(sentences=walks, vector_size=dimensions, window=window_size,negative=negative_samples, min_count=0, sg=1, compute_loss=True, workers=4, epochs=epochs)

    # Access the embedding matrix
    embedding_matrix = model.wv.vectors

    # Collect loss values over epochs
    loss_values = []
    for epoch in range(epochs):
        loss = model.get_latest_training_loss()
        loss_values.append(loss)
        print(f"Epoch {epoch + 1}/{epochs}, Loss: {loss}")

    # Plot the loss values
    plt.plot(range(1, epochs + 1), loss_values, marker='o')
    plt.title('Loss Over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.grid(True)
    plt.show()

    return embedding_matrix, loss_values

# Example usage
# embedding_matrix, loss_values = learn_embeddings(walks, dimensions=128, window_size=5, epochs=10)


In [19]:
johanna = Node2Vec(
    G,
    dimensions,
    walk_length,
    num_walks,
    p,
    q,
    learning_rate,
    window_size,
    epochs,
    negative_samples,
)

<IPython.core.display.Javascript object>

In [20]:
walks = []
for _ in range(num_walks):
    for node in G.nodes():
        walk = johanna.node2vec_walk(node)
        walks.append(walk)

<IPython.core.display.Javascript object>

In [21]:
walks

[[0, 4, 6, 5, 16, 5, 6, 16, 5, 0],
 [1, 13, 3, 0, 3, 0, 12, 3, 7, 2],
 [2, 13, 33, 31, 28, 33, 15, 32, 15, 33],
 [3, 2, 13, 0, 2, 7, 1, 2, 3, 1],
 [4, 0, 10, 4, 10, 0, 10, 4, 0, 6],
 [5, 16, 6, 5, 10, 0, 4, 10, 0, 1],
 [6, 5, 16, 6, 5, 16, 6, 0, 5, 16],
 [7, 3, 0, 12, 0, 19, 1, 3, 13, 2],
 [8, 0, 3, 2, 3, 13, 33, 13, 33, 14],
 [9, 2, 9, 2, 0, 3, 7, 1, 21, 0],
 [10, 4, 0, 6, 5, 6, 16, 5, 0, 8],
 [11, 0, 8, 33, 23, 33, 8, 0, 2, 8],
 [12, 3, 12, 0, 5, 0, 19, 1, 0, 7],
 [13, 0, 2, 7, 0, 12, 3, 2, 0, 1],
 [14, 32, 30, 33, 15, 32, 23, 29, 32, 23],
 [15, 33, 22, 33, 28, 33, 29, 32, 23, 33],
 [16, 6, 4, 0, 1, 17, 1, 17, 0, 12],
 [17, 1, 30, 8, 32, 8, 30, 8, 30, 32],
 [18, 32, 2, 27, 23, 27, 24, 27, 33, 14],
 [19, 0, 31, 0, 5, 0, 10, 5, 0, 10],
 [20, 32, 33, 26, 29, 26, 33, 22, 32, 31],
 [21, 1, 3, 0, 13, 1, 19, 0, 19, 1],
 [22, 32, 8, 32, 20, 33, 18, 32, 22, 33],
 [23, 33, 23, 27, 23, 33, 27, 23, 27, 33],
 [24, 25, 31, 28, 33, 31, 28, 33, 15, 33],
 [25, 31, 28, 31, 28, 33, 28, 31, 25, 31],
 [2

<IPython.core.display.Javascript object>

In [ ]:
from gensim.models import Word2Vec

In [ ]:
# learn_embeddings(walks, dimensions=dimensions, window_size=window_size, epochs=epochs, output_file="embeddings.bin")
embedding_matrix, loss_values = learn_embeddings(
    walks,
    dimensions=dimensions,
    negative=negative_samples,
    window_size=window_size,
    epochs=epochs,
)

In [ ]:
def loss_function(Z, S):
    """
    Calculate the objective function ||Z^T*Z - S||^2.

    Args:
        Z (numpy.ndarray): The node embeddings as a numpy array.
        S (numpy.ndarray): The similarity matrix.

    Returns:
        float: The value of the objective function.
    """
    Z_transpose = np.transpose(Z)
    diff = np.dot(Z_transpose, Z) - S
    #     obj_func = np.linalg.norm(diff) ** 2
    obj_func = np.linalg.norm(diff)
    return obj_func

In [ ]:
model = Node2Vec(G, dimensions, walk_length, num_walks, p, q, learning_rate, window_size, epochs, negative_samples)

In [ ]:
embeddings_bt = model.get_embeddings()

In [ ]:
embeddings_bt

In [ ]:
model.train(batch_size)

In [ ]:
# Get the node embeddings
Z =model.get_embeddings()

In [ ]:
Z = embedding_matrix.T

In [22]:
# Compute the similarity matrix
S = johanna.compute_similarity_matrix()

<IPython.core.display.Javascript object>

In [29]:
S[0]

array([1. , 0.3, 0.6, 0.6, 0.1, 0. , 0.1, 0.4, 0.1, 0.1, 0.2, 0.2, 0.1,
       0.6, 0. , 0. , 0.1, 0.5, 0. , 0.2, 0. , 0.3, 0. , 0.1, 0.1, 0.1,
       0. , 0.2, 0. , 0. , 0.2, 0.3, 0.1, 0.4])

<IPython.core.display.Javascript object>

In [31]:
S[2]

array([0.6, 0.6, 1. , 0.6, 0.1, 0.3, 0.1, 0.5, 0.5, 0.3, 0.2, 0.2, 0.1,
       0.2, 0.2, 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0.2, 0.2, 0.1, 0.2,
       0.1, 0.1, 0.1, 0. , 0.1, 0.2, 0.9, 0.6])

<IPython.core.display.Javascript object>

In [ ]:
# Calculate the objective function
obj_value = loss_function(Z, S)

In [ ]:
print("Objective Function Value:", obj_value)